// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using caominhhuy.Models;

#nullable disable

namespace caominhhuy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250527025401_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("caominhhuy.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kinh Tế"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Công Nghệ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Văn Học"
                        });
                });

            modelBuilder.Entity("caominhhuy.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Cuốn sách về nghệ thuật giao tiếp và xây dựng mối quan hệ",
                            ImageUrl = "/images/dacnhantam.jpg",
                            Name = "Đắc Nhân Tâm",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Hướng dẫn viết code sạch và dễ bảo trì",
                            ImageUrl = "/images/cleancode.jpg",
                            Name = "Clean Code",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Tác phẩm văn học thiếu nhi kinh điển",
                            ImageUrl = "/images/demen.jpg",
                            Name = "Dế Mèn Phiêu Lưu Ký",
                            Price = 90000m
                        });
                });

            modelBuilder.Entity("caominhhuy.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("caominhhuy.Models.Product", b =>
                {
                    b.HasOne("caominhhuy.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("caominhhuy.Models.ProductImage", b =>
                {
                    b.HasOne("caominhhuy.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("caominhhuy.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("caominhhuy.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
